INSERT INTO `Category` (name) VALUES ('Books');
INSERT INTO `Category` (name) VALUES ('Films');
INSERT INTO `Category` (name) VALUES ('Games');

INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (180.5,'JR Tolkien''s book','Lord of the Rings',200,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (120.5,'Unknow''s book','Hungry games',180,10);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (300.5,'The saga continue','The witcher 3',400,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (100.5,'First book','Game of thrones',120,10);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (180.5,'JR Tolkien''s book 2','Lord of the Rings 2',200,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (120.5,'Unknow''s book 2','Hungry games 2',180,10);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (300.5,'The saga continue 2','The witcher 3 2',400,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (100.5,'First book 2','Game of thrones 2 3',120,10);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (180.5,'JR Tolkien''s book 3','Lord of the Rings 3',200,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (120.5,'Unknow''s book 3','Hungry games 3',180,10);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (300.5,'The saga continue 3','The witcher 3 3',400,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (100.5,'First book 3','Game of thrones 3 4',120,10);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (180.5,'JR Tolkien''s book 4','Lord of the Rings 4',200,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (120.5,'Unknow''s book 4','Hungry games 4',180,10);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (300.5,'The saga continue 4','The witcher 3 4',400,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (100.5,'First book 4','Game of thrones 4',120,10);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (180.5,'JR Tolkien''s book 5','Lord of the Rings 5',200,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (120.5,'Unknow''s book 5','Hungry games 5',180,10);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (300.5,'The saga continue 5','The witcher 3 5',400,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (100.5,'First book 5','Game of thrones 5',120,10);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (180.5,'JR Tolkien''s book 6','Lord of the Rings 6',200,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (120.5,'Unknow''s book 6','Hungry games 6',180,10);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (300.5,'The saga continue 6','The witcher 3 6',400,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (100.5,'First book 6','Game of thrones 6',120,10);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (180.5,'JR Tolkien''s book 7','Lord of the Rings 7',200,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (120.5,'Unknow''s book 7','Hungry games 7',180,10);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (300.5,'The saga continue 7','The witcher 3 7',400,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (100.5,'First book 7','Game of thrones 7',120,10);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (180.5,'JR Tolkien''s book 8','Lord of the Rings 8',200,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (120.5,'Unknow''s book 8','Hungry games 8',180,10);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (300.5,'The saga continue 8','The witcher 3 8',400,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (100.5,'First book 8','Game of thrones 8',120,10);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (180.5,'JR Tolkien''s book 9','Lord of the Rings 9',200,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (120.5,'Unknow''s book 9','Hungry games 9',180,10);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (300.5,'The saga continue 9','The witcher 3 9',400,15);
INSERT INTO `Product` (`cost`, `description`, `name`, `rrp`,`productStock`) VALUES (100.5,'First book 9','Game of thrones 9',120,10);

INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (1,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (1,2);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (2,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (2,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (3,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (4,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (4,2);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (4,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (5,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (5,2);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (6,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (6,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (7,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (8,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (8,2);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (9,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (10,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (10,2);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (11,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (11,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (12,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (13,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (13,2);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (13,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (14,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (14,2);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (15,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (15,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (16,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (17,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (17,2);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (17,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (18,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (18,2);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (19,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (19,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (20,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (21,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (21,2);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (21,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (22,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (22,2);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (23,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (23,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (24,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (25,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (25,2);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (25,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (26,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (26,2);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (27,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (27,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (28,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (29,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (29,2);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (29,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (30,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (30,2);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (31,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (31,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (32,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (33,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (33,2);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (33,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (34,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (34,2);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (35,1);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (35,3);
INSERT INTO `Product_Category` (`product_id`, `category_id`) VALUES (36,3);

INSERT INTO `User` (`address1`, `address2`, `dob`, `email`, `firstname`, `isAdmin`, `lastname`, `password`, `postcode`, `telephone`, `town`) VALUES ('Dalbobranten 12','','1981-12-11','enkidugan@gmail.com','Jorge',1,'Legarre','password','12868','0735560243','Sköndal');
INSERT INTO `User` (`address1`, `address2`, `dob`, `email`, `firstname`, `isAdmin`, `lastname`, `password`, `postcode`, `telephone`, `town`) VALUES ('Ingen aning','','1980-06-06','mail2@gmail.com','Björn',0,'Göransson','password2','12331','0735555555','Stockholm');

insert into OrderStatus (`description`) values ('Placed');
insert into OrderStatus (`description`) values ('Handling');
insert into OrderStatus (`description`) values ('Shipped');
insert into OrderStatus (`description`) values ('Closed');
insert into OrderStatus (`description`) values ('Cancelled');

INSERT INTO `Orders` (`date`, `user_id`,`status_id`) VALUES (NOW(),1,1);
INSERT INTO `Orders` (`date`, `user_id`,`status_id`) VALUES (NOW(),2,4);
INSERT INTO `Orders` (`date`, `user_id`,`status_id`) VALUES (NOW(),1,2);

insert into `OrderDetail` (`order_id`,`productId`,`name`,`quantity`,`cost`,`rrp`) values (1,1,'Lord of the Rings',2,160.5,180);
insert into `OrderDetail` (`order_id`,`productId`,`name`,`quantity`,`cost`,`rrp`) values (1,2,'Hungry games',3,120.5,180);
insert into `OrderDetail` (`order_id`,`productId`,`name`,`quantity`,`cost`,`rrp`) values (2,1,'Lord of the Rings',1,180.5,200);
insert into `OrderDetail` (`order_id`,`productId`,`name`,`quantity`,`cost`,`rrp`) values (3,1,'Lord of the Rings',5,180.5,200);
insert into `OrderDetail` (`order_id`,`productId`,`name`,`quantity`,`cost`,`rrp`) values (3,2,'Hungry games',4,120.5,180);
